app/models.py
from datetime import datetime
from . import db
from flask_login import UserMixin
from app import login
from werkzeug.security import generate_password_hash, check_password_hash


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

# database tables
class User(UserMixin, db.Model):
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    id = db.Column(db.Integer, primary_key =True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(100))
    password_hash = db.Column(db.String(128))
    pitch = db.relationship('Pitch', backref='author', lazy=True)

    def __repr__(self) -> str:
        return f"User('{self.username}', '{self.email}')"

 
class Pitch(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    date_posted = db.Column(db.DateTime, default=datetime.utcnow)
    body = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Pitch('{self.title}', '{self.date_posted}', '{self.body}')"

app/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo,ValidationError
from app.models import User, Pitch

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit_form = SubmitField('Sign Up')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_form = SubmitField('Log in')

class PitchForm(FlaskForm):
    '''
    Class that handles pitch creation buy users
    '''
    title = StringField('Title', validators=[DataRequired()])
    body = StringField('Enter your pitch', validators=[DataRequired()])
    submit = SubmitField('Post') 


def validate_username(self, username):
    if User.query.filter_by(username=username.data).first():
        raise ValidationError("Username already taken!")

def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    # picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

app/__init__.py
from ensurepip import bootstrap
import logging
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
migrate = Migrate()
bcrypt = Bcrypt()
login = LoginManager()
login.login_view = 'main.login'
bootstrap = Bootstrap()

def createapp(config_class=Config):

    app = Flask(__name__)
    # Setting up configuration
    app.config.from_object(config_class)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config["SECRET_KEY"] = 'f46c992f38cf'

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    bcrypt.init_app(app)
    login.init_app(app) 

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    if not app.debug and not app.testing:
    #heroku logs to stdout
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
            # End of Heroku stdout logs


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

app/main/views.py
import os
import secrets
from flask import render_template, request, url_for,flash,redirect
from PIL import Image
import app
from ..forms import PitchForm, RegistrationForm, LoginForm, UpdateAccountForm
from app import db
from app.main import main
from  app.models import User, Pitch
from flask_login import current_user, login_required, login_user,logout_user

pitch = [
    {
        'author': 'Test User',
        'title': 'Test Pitch',
        'body': 'Test Tester Testing',
        'date_posted': 'May 6, 2020'
    },
    {
        'author': 'John User',
        'title': 'Johns Pitch',
        'body': 'John Tester Testing',
        'date_posted': 'May 2, 2020'
    }
]
@login_required
@main.route("/")
def index():
    pitch = Pitch.query.all()
    return render_template('index.html', pitch=pitch)

@main.route("/signup", methods=['GET', 'POST'])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Account successfully created for {form.username.data}', 'success')
        return redirect(url_for('main.login'))
    return render_template('signup.html', title='Register', form=form)


@main.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index')) #prevents the user from double logging in
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash(f'Not successfull', 'danger')
            return redirect(url_for('main.login'))
        login_user(user)    
        flash(f'Login Successful', 'success')
        return redirect(url_for ('main.index'))
    return render_template('login.html', title='Login', form=form)

@main.route('/logout')
def logout():
    '''
    Function that handles logout
    Returns:
        Log out user to login page
    '''
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/pitch/new', methods=['GET', 'POST'] )
def new_pitch():
    form=PitchForm()
    if form.validate_on_submit():
        pitch = Pitch(title=form.title.data, body=form.body.data)
        db.session.add(pitch)
        db.session.commit()
        flash('Your Pitch has been posted successfully!', 'success')
        return redirect(url_for('main.index'))
    return render_template('pitches.html',title='New Pitch', form=form)


# def save_picture(form_picture):
#     random_hex = secrets.token_hex(8)
#     _, f_ext = os.path.splitext(form_picture.filename)
#     picture_fn = random_hex + f_ext
#     picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)

#     output_size = (125, 125)
#     i = Image.open(form_picture)
#     i.thumbnail(output_size)
#     i.save(picture_path)

#     return picture_fn

@main.route("/profile", methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
            # if form.picture.data:
            # picture_file = save_picture(form.picture.data)
            # current_user.profilepic = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.add(pitch)
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('user.html', title='Profile', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PITCHLY | By Monica</title>
    <!-- Bootstrap CSS -->
    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  </head>
  <body class="font">
    <div>
      <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.profile', filename='user.html') }}">Profile</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.logout', filename='login.html') }}">Logout</a>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.new_pitch', filename='pitches.html') }}">New Pitch</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.signup', filename='signup.html') }}">SignUp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.login', filename='login.html') }}">Login</a>
          </li>
        {% endif %}
        </li>
      </ul>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %} {%if
          messages%} {%for category, message in messages %}
          <div class="alert alert-{{ category }}">{{message}}</div>
          {%endfor%} {%endif%} {% endwith %}
        </div>
      </div>
      {% block content %} {%endblock content%}
    </div>
    <div class="signup">{% block signup %} {%endblock signup%}</div>
    <div class="login">{% block login %} {%endblock login%}</div>
    <div>{% block profile %} {%endblock profile %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %} {% block content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='css/index.css') }}"
/>
<style>
  @import url("https://fonts.googleapis.com/css2?family=Space+Mono&display=swap");

  .font {
    font-family: "Space Mono", monospace;
  }
  .form-section {
    background-color: #101935;
    height: 100vh;
    width: 100vw;
  }
</style>
{% block pitch %}
<div>
  {% for pitch in pitch %}
  <div
    class="card text-center w-75 mx-auto mt-5"
    style="background-color: #564787; color: #DBCBD8;"
  >
    <div class="card-body">
      <h5 class="card-title fs-3 fw-bolder">{{ pitch.title }}</h5>
      <p class="card-text">📌 {{ pitch.body }}</p>
      <a href="#" class="btn btn-primary">Upvote</a>
      <div class="card-footer submit-btn">
        <p>Posted on {{pitch.date_posted}}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock pitch %} {% endblock %}

app/templates/login.html
{% extends "base.html" %} {% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<div class="form-section font flex justify-center items-center mx-auto">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group form-container justify-center items-center w-96 h-96  p-5 mx-auto">
            <h1 class="font-bold font text-xl text-center ">Welcome Back</h1>
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-md is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-md") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-md is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-md") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit_form(class="submit-btn") }}
        </div>
        <small class="text-muted ml-2 links">
            <a href="#">Forgot Password?</a>
        </small>
    </form>
    <div class="border-top pt-3 links">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('main.signup') }}">Sign Up Now</a>
        </small>
    </div>
</div>

{% endblock %}

app/templates/pitches.html
{% extends "base.html" %} {%block content%}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/pitches.css') }}">
<!-- form for creating a new pitch -->

<div class="form-section font flex justify-center items-center mx-auto">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group form-container justify-center items-center w-96 h-96  p-5 mx-auto">
            <h1 class="font-bold font text-xl text-center mb-5 ">Let's hear you!</h1>
            <legend class="border-bottom mb-5">Create New Pitch</legend>
            <div class="form-group te">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-md is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-sm") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body.label(class="form-control-label") }}
                {% if form.body.errors %}
                    {{ form.body(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.body.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.body(class="form-control form-control-sm") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group col-auto">
            {{ form.submit(class="button") }}
        </div>

  </div>
</div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %} {% block signup%}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/signup.css') }}">
<div class="form-section form-container font flex justify-center items-center mx-auto">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group justify-center items-center w-96 h-96  p-5 mx-auto">
            <h1 class="font-bold font text-xl text-center ">Register Here</h1>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {%if form.username.errors%}
                    {{ form.username(class="form-control form-control-md is-invalid") }}
                    <div class="invalid-feedback">
                        {%for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {%endfor%}
                    </div>
                {%else%}
                    {{ form.username(class="form-control form-control-md") }}
                {%endif%}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-md") }}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-md") }}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-md") }}
            </div>
            <div class=" mt-3 ">
                {{form.submit_form(class="submit-btn")}}
            </div>
        </fieldset>
        <div class="text-center mt-2">
            <small class="text-muted font-bold">
                Already Have an Account? <a href="{{url_for('main.login')}}">Login</a>
            </small>
        </div>
    </form>
</div>
{% endblock signup %}

app/templates/user.html
{% extends "base.html" %}
{% block profilecontent %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ profilepic }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock profilecontent %}